version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: busca-servicos-app
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: busca_servicos_db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=busca_servico

  pgadmin:
    image: dpage/pgadmin4
    container_name: busca-servico-pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - "8000:80"
    depends_on:
      - db
